### ISSUE TITLE
Default stroke color

### ISSUE THREAD

**Issue by 1j01** [epistemex/8-bit#3]
In `CanvasRenderingContext2D`, the `fillStyle` and `strokeStyle` both default to black, whereas with 8-bit, the stroke color defaults to white/light.

**Comment by epistemex** [comment]
It is pretty much due to the lack of alpha channel which makes the background white. I can reconsider this though (as part of strict mode).

**Comment by epistemex** [comment]
And of course, to reflect the more traditional use of palette background typically defaults to index 0 and "pen color" to index 1 which would be black and white in most palettes. Won't fix for now.
